/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package PkgVue;

import PkgEntite.Attribution;
import PkgEntite.Etablissement;
import PkgEntite.Groupe;
import PkgEntite.Offre;
import java.util.Iterator;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Query;

/**
 *
 * @author DrkuHybride
 */
public class jpAttribution extends javax.swing.JPanel {

    /**
     * Creates new form jpAttribution
     */
    public jpAttribution() {
        initComponents();
         chargerEtabl();
         chargerGroupes();
    }
     private String getEtabId(String pEtabNom)
        {                       
             String sReq = "From Etablissement Where Eta_Nom = ?";
            jfPrincipal.getSession().beginTransaction();
            Query q = jfPrincipal.getSession().createQuery(sReq);
            q.setParameter(0, pEtabNom);
            Etablissement  unEtabli = (Etablissement)q.uniqueResult();          
            String EtabId =  (String) unEtabli.getEtaId();
            return EtabId;
            
         
        }
     
     private String getGroupId(String pGroupNom)
     {
          String sReq = "From Groupe Where GP_Nom =?";
          jfPrincipal.getSession().beginTransaction();
          Query q = jfPrincipal.getSession().createQuery(sReq);
          q.setParameter(0, pGroupNom);
          Groupe  unGroupe = (Groupe)q.uniqueResult();          
          String GroupId =  (String) unGroupe.getGpId();
          return GroupId;
     }
     
     private void chargerEtabl()
        {
            /** on recupere les informations de la table Etablissement
             * puis on ajoute à la liste un élément avec le nom de l'établissement
             */
            String sReq = "From Etablissement";           
            jfPrincipal.getSession().beginTransaction();
            Query q = jfPrincipal.getSession().createQuery(sReq); 
            jcmbEtablissement.removeAllItems();            
            Iterator etabli = q.iterate(); //--> import java.util.Iterator;
            while (etabli.hasNext())
            {
                Etablissement unEtabli = (Etablissement) etabli.next();
                jcmbEtablissement.addItem(unEtabli.getEtaNom());
            }
           
            
         }
     
     private void chargerGroupes()
     {
          String sReq = "From Groupe";           
            jfPrincipal.getSession().beginTransaction();
            Query q = jfPrincipal.getSession().createQuery(sReq); 
            jcmbGroupe.removeAllItems();            
            Iterator Group = q.iterate(); //--> import java.util.Iterator;
            while (Group.hasNext())
            {
                Groupe unGroupe = (Groupe) Group.next();
                jcmbGroupe.addItem(unGroupe.getGpNom());
            }
     }
     
     private void chargerChambres(String pEtaId, String pGroupId)
     {        
         /** 
          * on charge le nombre de chambres correspondant à l'id de l'établissement et l'id du
          * type de chambre. Le nombre de chambres sera ensuite transmis au texte
          */
        
            int nbligne;
            int i;
            nbligne = jtableChambre.getRowCount();
            if(nbligne >= 0)
            {
                for(i=0;i <nbligne; i++)
                {
                    ((DefaultTableModel)jtableChambre.getModel()).removeRow(0);
                }
               
                 String sReq = "From Attribution Where Att_Etablissement = ? And Att_Groupe = ?";
                 Query q = jfPrincipal.getSession().createQuery(sReq);
                 q.setParameter(0, pEtaId);
                 q.setParameter(1, pGroupId);
        
                Iterator Attri = q.iterate();             
                while(Attri.hasNext())
                {
                    Attribution uneAttribution = (Attribution) Attri.next();
                    ((DefaultTableModel) jtableChambre.getModel()).addRow(new Object[] {uneAttribution.getOffre().getTypechambre().getTchId(), uneAttribution.getAttNbchambres()});
                }
            
            
        }
     }
     
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcmbEtablissement = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtableChambre = new javax.swing.JTable();
        jcmbGroupe = new javax.swing.JComboBox();
        jbCharger = new javax.swing.JButton();

        jcmbEtablissement.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Collège de Moka" }));
        jcmbEtablissement.setToolTipText("");
        jcmbEtablissement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbEtablissementActionPerformed(evt);
            }
        });

        jtableChambre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Type Chambre", "Nombre chambres"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtableChambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtableChambreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtableChambre);

        jcmbGroupe.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Groupe folklorique du Bachkortostan" }));
        jcmbGroupe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jcmbGroupeMouseClicked(evt);
            }
        });
        jcmbGroupe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbGroupeActionPerformed(evt);
            }
        });

        jbCharger.setText("Charger");
        jbCharger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jbChargerMouseClicked(evt);
            }
        });
        jbCharger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbChargerActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(143, 143, 143)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jcmbEtablissement, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jcmbGroupe, 0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jbCharger)
                .add(173, 173, 173))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(32, 32, 32)
                .add(jcmbEtablissement, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jcmbGroupe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jbCharger)
                .add(5, 5, 5)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 172, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(167, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtableChambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtableChambreMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jtableChambreMouseClicked

    private void jcmbEtablissementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbEtablissementActionPerformed
        // TODO add your handling code here:
        String EtabNom = (String) jcmbEtablissement.getSelectedItem();
         String GroupNom = (String) jcmbGroupe.getSelectedItem(); 
            if ((EtabNom != null)&&(GroupNom != null))
            {
                String EtabId = getEtabId(EtabNom);
                String GroupId = getGroupId(GroupNom);
                chargerChambres(EtabId, GroupId);
            }
         
            
    }//GEN-LAST:event_jcmbEtablissementActionPerformed

    private void jcmbGroupeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbGroupeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcmbGroupeActionPerformed

    private void jcmbGroupeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jcmbGroupeMouseClicked
        // TODO add your handling code here:
         String EtabNom = (String) jcmbEtablissement.getSelectedItem();
         String GroupNom = (String) jcmbGroupe.getSelectedItem(); 
            if ((EtabNom != null)&&(GroupNom != null))
            {
                String EtabId = getEtabId(EtabNom);
                String GroupId = getGroupId(GroupNom);
                chargerChambres(EtabId, GroupId);
            }
        
    }//GEN-LAST:event_jcmbGroupeMouseClicked

    private void jbChargerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbChargerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbChargerActionPerformed

    private void jbChargerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jbChargerMouseClicked
        // TODO add your handling code here:
         String EtabNom = (String) jcmbEtablissement.getSelectedItem();
         String GroupNom = (String) jcmbGroupe.getSelectedItem(); 
            if ((EtabNom != null)&&(GroupNom != null))
            {
                String EtabId = getEtabId(EtabNom);
                String GroupId = getGroupId(GroupNom);
                chargerChambres(EtabId, GroupId);
            }
    }//GEN-LAST:event_jbChargerMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCharger;
    private javax.swing.JComboBox jcmbEtablissement;
    private javax.swing.JComboBox jcmbGroupe;
    private javax.swing.JTable jtableChambre;
    // End of variables declaration//GEN-END:variables
}
